// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_roles.sql

package dbsqlc

import (
	"context"
)

const getAuthRole = `-- name: GetAuthRole :one
SELECT id, tenant, name, labels, spec, status, resource_version, deleted_at, created_at, updated_at
FROM auth_roles
WHERE tenant = $1
  AND name = $2
  AND deleted_at IS NULL
`

type GetAuthRoleParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
}

func (q *Queries) GetAuthRole(ctx context.Context, arg GetAuthRoleParams) (AuthRole, error) {
	row := q.db.QueryRow(ctx, getAuthRole, arg.Tenant, arg.Name)
	var i AuthRole
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Name,
		&i.Labels,
		&i.Spec,
		&i.Status,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthRolesByTenant = `-- name: ListAuthRolesByTenant :many
SELECT id, tenant, name, labels, spec, status, resource_version, deleted_at, created_at, updated_at
FROM auth_roles
WHERE tenant = $1
  AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListAuthRolesByTenant(ctx context.Context, tenant string) ([]AuthRole, error) {
	rows, err := q.db.Query(ctx, listAuthRolesByTenant, tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthRole{}
	for rows.Next() {
		var i AuthRole
		if err := rows.Scan(
			&i.ID,
			&i.Tenant,
			&i.Name,
			&i.Labels,
			&i.Spec,
			&i.Status,
			&i.ResourceVersion,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAuthRole = `-- name: SoftDeleteAuthRole :execrows
UPDATE auth_roles
SET
  deleted_at = NOW(),
  resource_version = resource_version + 1,
  updated_at = NOW()
WHERE tenant = $1
  AND name = $2
  AND deleted_at IS NULL
`

type SoftDeleteAuthRoleParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
}

func (q *Queries) SoftDeleteAuthRole(ctx context.Context, arg SoftDeleteAuthRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAuthRole, arg.Tenant, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAuthRole = `-- name: UpsertAuthRole :one
INSERT INTO auth_roles (
  tenant, name, labels, spec, status
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (tenant, name) DO UPDATE
SET
  labels = EXCLUDED.labels,
  spec = EXCLUDED.spec,
  status = EXCLUDED.status,
  resource_version = auth_roles.resource_version + 1,
  deleted_at = NULL,
  updated_at = NOW()
RETURNING id, tenant, name, labels, spec, status, resource_version, deleted_at, created_at, updated_at
`

type UpsertAuthRoleParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
	Labels []byte `json:"labels"`
	Spec   []byte `json:"spec"`
	Status []byte `json:"status"`
}

func (q *Queries) UpsertAuthRole(ctx context.Context, arg UpsertAuthRoleParams) (AuthRole, error) {
	row := q.db.QueryRow(ctx, upsertAuthRole,
		arg.Tenant,
		arg.Name,
		arg.Labels,
		arg.Spec,
		arg.Status,
	)
	var i AuthRole
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Name,
		&i.Labels,
		&i.Spec,
		&i.Status,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
