// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_role_assignments.sql

package dbsqlc

import (
	"context"
)

const getAuthRoleAssignment = `-- name: GetAuthRoleAssignment :one
SELECT id, tenant, name, labels, spec, status, resource_version, deleted_at, created_at, updated_at
FROM auth_role_assignments
WHERE tenant = $1
  AND name = $2
  AND deleted_at IS NULL
`

type GetAuthRoleAssignmentParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
}

func (q *Queries) GetAuthRoleAssignment(ctx context.Context, arg GetAuthRoleAssignmentParams) (AuthRoleAssignment, error) {
	row := q.db.QueryRow(ctx, getAuthRoleAssignment, arg.Tenant, arg.Name)
	var i AuthRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Name,
		&i.Labels,
		&i.Spec,
		&i.Status,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthRoleAssignmentsByTenant = `-- name: ListAuthRoleAssignmentsByTenant :many
SELECT id, tenant, name, labels, spec, status, resource_version, deleted_at, created_at, updated_at
FROM auth_role_assignments
WHERE tenant = $1
  AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListAuthRoleAssignmentsByTenant(ctx context.Context, tenant string) ([]AuthRoleAssignment, error) {
	rows, err := q.db.Query(ctx, listAuthRoleAssignmentsByTenant, tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthRoleAssignment{}
	for rows.Next() {
		var i AuthRoleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.Tenant,
			&i.Name,
			&i.Labels,
			&i.Spec,
			&i.Status,
			&i.ResourceVersion,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAuthRoleAssignment = `-- name: SoftDeleteAuthRoleAssignment :execrows
UPDATE auth_role_assignments
SET
  deleted_at = NOW(),
  resource_version = resource_version + 1,
  updated_at = NOW()
WHERE tenant = $1
  AND name = $2
  AND deleted_at IS NULL
`

type SoftDeleteAuthRoleAssignmentParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
}

func (q *Queries) SoftDeleteAuthRoleAssignment(ctx context.Context, arg SoftDeleteAuthRoleAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAuthRoleAssignment, arg.Tenant, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAuthRoleAssignment = `-- name: UpsertAuthRoleAssignment :one
INSERT INTO auth_role_assignments (
  tenant, name, labels, spec, status
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (tenant, name) DO UPDATE
SET
  labels = EXCLUDED.labels,
  spec = EXCLUDED.spec,
  status = EXCLUDED.status,
  resource_version = auth_role_assignments.resource_version + 1,
  deleted_at = NULL,
  updated_at = NOW()
RETURNING id, tenant, name, labels, spec, status, resource_version, deleted_at, created_at, updated_at
`

type UpsertAuthRoleAssignmentParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
	Labels []byte `json:"labels"`
	Spec   []byte `json:"spec"`
	Status []byte `json:"status"`
}

func (q *Queries) UpsertAuthRoleAssignment(ctx context.Context, arg UpsertAuthRoleAssignmentParams) (AuthRoleAssignment, error) {
	row := q.db.QueryRow(ctx, upsertAuthRoleAssignment,
		arg.Tenant,
		arg.Name,
		arg.Labels,
		arg.Spec,
		arg.Status,
	)
	var i AuthRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Name,
		&i.Labels,
		&i.Spec,
		&i.Status,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
