// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Operation struct {
	ID               int64              `json:"id"`
	OperationID      string             `json:"operation_id"`
	SecaRef          string             `json:"seca_ref"`
	ProviderActionID pgtype.Text        `json:"provider_action_id"`
	Phase            string             `json:"phase"`
	ErrorText        pgtype.Text        `json:"error_text"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ResourceBinding struct {
	ID          int64              `json:"id"`
	Tenant      string             `json:"tenant"`
	Workspace   string             `json:"workspace"`
	Kind        string             `json:"kind"`
	SecaRef     string             `json:"seca_ref"`
	ProviderRef string             `json:"provider_ref"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
