// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthRole struct {
	ID              int64              `json:"id"`
	Tenant          string             `json:"tenant"`
	Name            string             `json:"name"`
	Labels          []byte             `json:"labels"`
	Spec            []byte             `json:"spec"`
	Status          []byte             `json:"status"`
	ResourceVersion int64              `json:"resource_version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AuthRoleAssignment struct {
	ID              int64              `json:"id"`
	Tenant          string             `json:"tenant"`
	Name            string             `json:"name"`
	Labels          []byte             `json:"labels"`
	Spec            []byte             `json:"spec"`
	Status          []byte             `json:"status"`
	ResourceVersion int64              `json:"resource_version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Operation struct {
	ID               int64              `json:"id"`
	OperationID      string             `json:"operation_id"`
	SecaRef          string             `json:"seca_ref"`
	ProviderActionID pgtype.Text        `json:"provider_action_id"`
	Phase            string             `json:"phase"`
	ErrorText        pgtype.Text        `json:"error_text"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ResourceBinding struct {
	ID          int64              `json:"id"`
	Tenant      string             `json:"tenant"`
	Workspace   string             `json:"workspace"`
	Kind        string             `json:"kind"`
	SecaRef     string             `json:"seca_ref"`
	ProviderRef string             `json:"provider_ref"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceProviderCredential struct {
	ID                int64              `json:"id"`
	Tenant            string             `json:"tenant"`
	Workspace         string             `json:"workspace"`
	Provider          string             `json:"provider"`
	ProjectRef        pgtype.Text        `json:"project_ref"`
	ApiEndpoint       pgtype.Text        `json:"api_endpoint"`
	ApiTokenEncrypted string             `json:"api_token_encrypted"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}
