// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: operations.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (
  operation_id, seca_ref, provider_action_id, phase, error_text
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, operation_id, seca_ref, provider_action_id, phase, error_text, created_at, updated_at
`

type CreateOperationParams struct {
	OperationID      string      `json:"operation_id"`
	SecaRef          string      `json:"seca_ref"`
	ProviderActionID pgtype.Text `json:"provider_action_id"`
	Phase            string      `json:"phase"`
	ErrorText        pgtype.Text `json:"error_text"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.OperationID,
		arg.SecaRef,
		arg.ProviderActionID,
		arg.Phase,
		arg.ErrorText,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.SecaRef,
		&i.ProviderActionID,
		&i.Phase,
		&i.ErrorText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationByID = `-- name: GetOperationByID :one
SELECT id, operation_id, seca_ref, provider_action_id, phase, error_text, created_at, updated_at
FROM operations
WHERE operation_id = $1
`

func (q *Queries) GetOperationByID(ctx context.Context, operationID string) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByID, operationID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.SecaRef,
		&i.ProviderActionID,
		&i.Phase,
		&i.ErrorText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
