// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resource_bindings.sql

package dbsqlc

import (
	"context"
)

const createResourceBinding = `-- name: CreateResourceBinding :one
INSERT INTO resource_bindings (
  tenant, workspace, kind, seca_ref, provider_ref, status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant, workspace, kind, seca_ref, provider_ref, status, created_at, updated_at
`

type CreateResourceBindingParams struct {
	Tenant      string `json:"tenant"`
	Workspace   string `json:"workspace"`
	Kind        string `json:"kind"`
	SecaRef     string `json:"seca_ref"`
	ProviderRef string `json:"provider_ref"`
	Status      string `json:"status"`
}

func (q *Queries) CreateResourceBinding(ctx context.Context, arg CreateResourceBindingParams) (ResourceBinding, error) {
	row := q.db.QueryRow(ctx, createResourceBinding,
		arg.Tenant,
		arg.Workspace,
		arg.Kind,
		arg.SecaRef,
		arg.ProviderRef,
		arg.Status,
	)
	var i ResourceBinding
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Workspace,
		&i.Kind,
		&i.SecaRef,
		&i.ProviderRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceBindingBySecaRef = `-- name: GetResourceBindingBySecaRef :one
SELECT id, tenant, workspace, kind, seca_ref, provider_ref, status, created_at, updated_at
FROM resource_bindings
WHERE seca_ref = $1
`

func (q *Queries) GetResourceBindingBySecaRef(ctx context.Context, secaRef string) (ResourceBinding, error) {
	row := q.db.QueryRow(ctx, getResourceBindingBySecaRef, secaRef)
	var i ResourceBinding
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Workspace,
		&i.Kind,
		&i.SecaRef,
		&i.ProviderRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
