// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspace_provider_credentials.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspaceProviderCredential = `-- name: GetWorkspaceProviderCredential :one
SELECT id, tenant, workspace, provider, project_ref, api_endpoint, api_token_encrypted, created_at, updated_at, deleted_at
FROM workspace_provider_credentials
WHERE tenant = $1
  AND workspace = $2
  AND provider = $3
  AND deleted_at IS NULL
LIMIT 1
`

type GetWorkspaceProviderCredentialParams struct {
	Tenant    string `json:"tenant"`
	Workspace string `json:"workspace"`
	Provider  string `json:"provider"`
}

func (q *Queries) GetWorkspaceProviderCredential(ctx context.Context, arg GetWorkspaceProviderCredentialParams) (WorkspaceProviderCredential, error) {
	row := q.db.QueryRow(ctx, getWorkspaceProviderCredential, arg.Tenant, arg.Workspace, arg.Provider)
	var i WorkspaceProviderCredential
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Workspace,
		&i.Provider,
		&i.ProjectRef,
		&i.ApiEndpoint,
		&i.ApiTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteWorkspaceProviderCredential = `-- name: SoftDeleteWorkspaceProviderCredential :execrows
UPDATE workspace_provider_credentials
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE tenant = $1
  AND workspace = $2
  AND provider = $3
  AND deleted_at IS NULL
`

type SoftDeleteWorkspaceProviderCredentialParams struct {
	Tenant    string `json:"tenant"`
	Workspace string `json:"workspace"`
	Provider  string `json:"provider"`
}

func (q *Queries) SoftDeleteWorkspaceProviderCredential(ctx context.Context, arg SoftDeleteWorkspaceProviderCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWorkspaceProviderCredential, arg.Tenant, arg.Workspace, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWorkspaceProviderCredential = `-- name: UpsertWorkspaceProviderCredential :one
INSERT INTO workspace_provider_credentials (
  tenant, workspace, provider, project_ref, api_endpoint, api_token_encrypted
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (tenant, workspace, provider) DO UPDATE SET
  project_ref = EXCLUDED.project_ref,
  api_endpoint = EXCLUDED.api_endpoint,
  api_token_encrypted = EXCLUDED.api_token_encrypted,
  deleted_at = NULL,
  updated_at = NOW()
RETURNING id, tenant, workspace, provider, project_ref, api_endpoint, api_token_encrypted, created_at, updated_at, deleted_at
`

type UpsertWorkspaceProviderCredentialParams struct {
	Tenant            string      `json:"tenant"`
	Workspace         string      `json:"workspace"`
	Provider          string      `json:"provider"`
	ProjectRef        pgtype.Text `json:"project_ref"`
	ApiEndpoint       pgtype.Text `json:"api_endpoint"`
	ApiTokenEncrypted string      `json:"api_token_encrypted"`
}

func (q *Queries) UpsertWorkspaceProviderCredential(ctx context.Context, arg UpsertWorkspaceProviderCredentialParams) (WorkspaceProviderCredential, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceProviderCredential,
		arg.Tenant,
		arg.Workspace,
		arg.Provider,
		arg.ProjectRef,
		arg.ApiEndpoint,
		arg.ApiTokenEncrypted,
	)
	var i WorkspaceProviderCredential
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Workspace,
		&i.Provider,
		&i.ProjectRef,
		&i.ApiEndpoint,
		&i.ApiTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
