// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspaces.sql

package dbsqlc

import (
	"context"
)

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, tenant, name, region, labels, spec, status, resource_version, deleted_at, created_at, updated_at
FROM workspaces
WHERE tenant = $1
  AND name = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetWorkspaceParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
}

func (q *Queries) GetWorkspace(ctx context.Context, arg GetWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, arg.Tenant, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Name,
		&i.Region,
		&i.Labels,
		&i.Spec,
		&i.Status,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspacesByTenant = `-- name: ListWorkspacesByTenant :many
SELECT id, tenant, name, region, labels, spec, status, resource_version, deleted_at, created_at, updated_at
FROM workspaces
WHERE tenant = $1
  AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListWorkspacesByTenant(ctx context.Context, tenant string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByTenant, tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Tenant,
			&i.Name,
			&i.Region,
			&i.Labels,
			&i.Spec,
			&i.Status,
			&i.ResourceVersion,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :execrows
UPDATE workspaces
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE tenant = $1
  AND name = $2
  AND deleted_at IS NULL
`

type SoftDeleteWorkspaceParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
}

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, arg SoftDeleteWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWorkspace, arg.Tenant, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (
  tenant, name, region, labels, spec, status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (tenant, name) DO UPDATE SET
  region = EXCLUDED.region,
  labels = EXCLUDED.labels,
  spec = EXCLUDED.spec,
  status = EXCLUDED.status,
  resource_version = workspaces.resource_version + 1,
  deleted_at = NULL,
  updated_at = NOW()
RETURNING id, tenant, name, region, labels, spec, status, resource_version, deleted_at, created_at, updated_at
`

type UpsertWorkspaceParams struct {
	Tenant string `json:"tenant"`
	Name   string `json:"name"`
	Region string `json:"region"`
	Labels []byte `json:"labels"`
	Spec   []byte `json:"spec"`
	Status []byte `json:"status"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace,
		arg.Tenant,
		arg.Name,
		arg.Region,
		arg.Labels,
		arg.Spec,
		arg.Status,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Name,
		&i.Region,
		&i.Labels,
		&i.Spec,
		&i.Status,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
